"""initial schema

Revision ID: d7dea236a1ba
Revises: 
Create Date: 2026-09-12 19:28:58.374676
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd7dea236a1ba'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_distances',
    sa.Column('from_district', sa.String(length=80), nullable=False),
    sa.Column('to_district', sa.String(length=80), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('basis', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('from_district', 'to_district')
    )
    op.create_table('districts',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('hq_town', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('enterprises',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('name_source', sa.String(length=24), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('pincode', sa.String(length=16), nullable=False),
    sa.Column('nic5_code', sa.String(length=8), nullable=False),
    sa.Column('nic2_division', sa.String(length=4), nullable=False),
    sa.Column('nic_description', sa.Text(), nullable=False),
    sa.Column('registration_date', sa.String(length=24), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enterprises_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_enterprises_nic2_division'), ['nic2_division'], unique=False)
        batch_op.create_index(batch_op.f('ix_enterprises_nic5_code'), ['nic5_code'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'endpoint', 'key', name='uq_idempotency_scope')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_business_id'), ['business_id'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receiving_processes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('nic5_codes', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('enterprise_id', sa.String(length=24), nullable=True),
    sa.Column('is_buyer', sa.Boolean(), nullable=False),
    sa.Column('is_seller', sa.Boolean(), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('location_precision', sa.String(length=24), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_enterprise_id'), ['enterprise_id'], unique=False)

    op.create_table('enterprise_byproducts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('enterprise_id', sa.String(length=24), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=True),
    sa.Column('byproduct_name', sa.String(length=120), nullable=False),
    sa.Column('waste_ratio_pct', sa.Float(), nullable=False),
    sa.Column('annual_tonnes_estimated', sa.Float(), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('source_citation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprise_byproducts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enterprise_byproducts_enterprise_id'), ['enterprise_id'], unique=False)

    op.create_table('material_aliases',
    sa.Column('alias', sa.String(length=160), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('alias')
    )
    op.create_table('material_compatibility_flags',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.Column('receiving_process_id', sa.String(length=64), nullable=False),
    sa.Column('contamination_keyword', sa.String(length=80), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['receiving_process_id'], ['receiving_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_compatibility_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_compatibility_flags_material_id'), ['material_id'], unique=False)

    op.create_table('receiving_process_materials',
    sa.Column('process_id', sa.String(length=64), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['receiving_processes.id'], ),
    sa.PrimaryKeyConstraint('process_id', 'material_id')
    )
    op.create_table('symbiosis_pathways',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('producer_nic2', sa.String(length=4), nullable=False),
    sa.Column('producer_industry', sa.String(length=160), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=True),
    sa.Column('byproduct_name', sa.String(length=120), nullable=False),
    sa.Column('byproduct_type', sa.String(length=80), nullable=False),
    sa.Column('receiver_nic2', sa.String(length=4), nullable=False),
    sa.Column('receiver_industry', sa.String(length=160), nullable=False),
    sa.Column('use_case', sa.Text(), nullable=False),
    sa.Column('source_citation', sa.Text(), nullable=False),
    sa.Column('receiving_process_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['receiving_process_id'], ['receiving_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('supabase_user_id', sa.String(length=64), nullable=True),
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_users_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_users_supabase_user_id'), ['supabase_user_id'], unique=True)

    op.create_table('business_receiving_processes',
    sa.Column('business_id', sa.String(length=40), nullable=False),
    sa.Column('process_id', sa.String(length=64), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['receiving_processes.id'], ),
    sa.PrimaryKeyConstraint('business_id', 'process_id')
    )
    op.create_table('listings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('seller_business_id', sa.String(length=40), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.Column('available_quantity_kg', sa.Integer(), nullable=False),
    sa.Column('asking_price_paise_per_tonne', sa.Integer(), nullable=False),
    sa.Column('seller_floor_paise_per_tonne', sa.Integer(), nullable=False),
    sa.Column('moisture_pct', sa.Float(), nullable=False),
    sa.Column('contamination_notes', sa.Text(), nullable=False),
    sa.Column('pickup_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pickup_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('location_precision', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('asking_price_paise_per_tonne >= 0', name='ck_listing_price_nonneg'),
    sa.CheckConstraint('available_quantity_kg >= 0', name='ck_listing_qty_nonneg'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['seller_business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_district'), ['district'], unique=False)
        batch_op.create_index('ix_listings_material_status', ['material_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_seller_business_id'), ['seller_business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    op.create_table('requirements',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('buyer_business_id', sa.String(length=40), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.Column('receiving_process_id', sa.String(length=64), nullable=False),
    sa.Column('quantity_kg', sa.Integer(), nullable=False),
    sa.Column('max_moisture_pct', sa.Float(), nullable=False),
    sa.Column('delivery_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('buyer_max_total_paise', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('location_precision', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_kg > 0', name='ck_requirement_qty_positive'),
    sa.ForeignKeyConstraint(['buyer_business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['receiving_process_id'], ['receiving_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_buyer_business_id'), ['buyer_business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_status'), ['status'], unique=False)

    op.create_table('negotiations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('requirement_id', sa.String(length=40), nullable=False),
    sa.Column('buyer_business_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('current_listing_id', sa.String(length=40), nullable=True),
    sa.Column('failure_code', sa.String(length=40), nullable=True),
    sa.Column('deal_id', sa.String(length=40), nullable=True),
    sa.Column('agent_mode', sa.String(length=16), nullable=False),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['current_listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('negotiations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiations_buyer_business_id'), ['buyer_business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_negotiations_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index('ix_negotiations_requirement_status', ['requirement_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_negotiations_status'), ['status'], unique=False)

    op.create_table('transport_options',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('listing_id', sa.String(length=40), nullable=False),
    sa.Column('requirement_id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('freight_paise', sa.Integer(), nullable=False),
    sa.Column('capacity_kg', sa.Integer(), nullable=False),
    sa.Column('pickup_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('distance_basis', sa.String(length=32), nullable=False),
    sa.Column('created_by_business_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('capacity_kg > 0', name='ck_transport_capacity_positive'),
    sa.CheckConstraint('freight_paise >= 0', name='ck_transport_freight_nonneg'),
    sa.ForeignKeyConstraint(['created_by_business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transport_options_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transport_options_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index('ix_transport_pair', ['listing_id', 'requirement_id'], unique=False)

    op.create_table('negotiation_candidates',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('negotiation_id', sa.String(length=40), nullable=False),
    sa.Column('listing_id', sa.String(length=40), nullable=False),
    sa.Column('seller_business_id', sa.String(length=40), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=True),
    sa.Column('rounds_used', sa.Integer(), nullable=False),
    sa.Column('best_offer_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ),
    sa.ForeignKeyConstraint(['seller_business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negotiation_id', 'listing_id', name='uq_candidate_per_negotiation')
    )
    with op.batch_alter_table('negotiation_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiation_candidates_negotiation_id'), ['negotiation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_negotiation_candidates_seller_business_id'), ['seller_business_id'], unique=False)

    op.create_table('negotiation_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('negotiation_id', sa.String(length=40), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('offer_id', sa.String(length=40), nullable=True),
    sa.Column('listing_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negotiation_id', 'seq', name='uq_event_seq_per_negotiation')
    )
    with op.batch_alter_table('negotiation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_negotiation_events_negotiation_id'), ['negotiation_id'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('negotiation_id', sa.String(length=40), nullable=False),
    sa.Column('listing_id', sa.String(length=40), nullable=False),
    sa.Column('transport_option_id', sa.String(length=40), nullable=False),
    sa.Column('quantity_kg', sa.Integer(), nullable=False),
    sa.Column('unit_price_paise_per_tonne', sa.Integer(), nullable=False),
    sa.Column('material_paise', sa.Integer(), nullable=False),
    sa.Column('freight_paise', sa.Integer(), nullable=False),
    sa.Column('buyer_total_paise', sa.Integer(), nullable=False),
    sa.Column('seller_receives_paise', sa.Integer(), nullable=False),
    sa.Column('pickup_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('author', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('responds_to_offer_id', sa.String(length=40), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ),
    sa.ForeignKeyConstraint(['transport_option_id'], ['transport_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_negotiation_id'), ['negotiation_id'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('negotiation_id', sa.String(length=40), nullable=False),
    sa.Column('requirement_id', sa.String(length=40), nullable=False),
    sa.Column('listing_id', sa.String(length=40), nullable=False),
    sa.Column('offer_id', sa.String(length=40), nullable=False),
    sa.Column('seller_business_id', sa.String(length=40), nullable=False),
    sa.Column('buyer_business_id', sa.String(length=40), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.Column('intended_use', sa.Text(), nullable=False),
    sa.Column('quantity_kg', sa.Integer(), nullable=False),
    sa.Column('unit_price_paise_per_tonne', sa.Integer(), nullable=False),
    sa.Column('material_paise', sa.Integer(), nullable=False),
    sa.Column('freight_paise', sa.Integer(), nullable=False),
    sa.Column('buyer_total_paise', sa.Integer(), nullable=False),
    sa.Column('seller_receives_paise', sa.Integer(), nullable=False),
    sa.Column('transport_option_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('stock_released', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['negotiation_id'], ['negotiations.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.ForeignKeyConstraint(['seller_business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['transport_option_id'], ['transport_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', name='uq_deal_per_requirement')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_buyer_business_id'), ['buyer_business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_seller_business_id'), ['seller_business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_status'))
        batch_op.drop_index(batch_op.f('ix_deals_seller_business_id'))
        batch_op.drop_index(batch_op.f('ix_deals_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_deals_listing_id'))
        batch_op.drop_index(batch_op.f('ix_deals_buyer_business_id'))

    op.drop_table('deals')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_negotiation_id'))
        batch_op.drop_index(batch_op.f('ix_offers_listing_id'))

    op.drop_table('offers')
    with op.batch_alter_table('negotiation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiation_events_negotiation_id'))

    op.drop_table('negotiation_events')
    with op.batch_alter_table('negotiation_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiation_candidates_seller_business_id'))
        batch_op.drop_index(batch_op.f('ix_negotiation_candidates_negotiation_id'))

    op.drop_table('negotiation_candidates')
    with op.batch_alter_table('transport_options', schema=None) as batch_op:
        batch_op.drop_index('ix_transport_pair')
        batch_op.drop_index(batch_op.f('ix_transport_options_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_transport_options_listing_id'))

    op.drop_table('transport_options')
    with op.batch_alter_table('negotiations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_negotiations_status'))
        batch_op.drop_index('ix_negotiations_requirement_status')
        batch_op.drop_index(batch_op.f('ix_negotiations_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_negotiations_buyer_business_id'))

    op.drop_table('negotiations')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_status'))
        batch_op.drop_index(batch_op.f('ix_requirements_district'))
        batch_op.drop_index(batch_op.f('ix_requirements_buyer_business_id'))

    op.drop_table('requirements')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_index(batch_op.f('ix_listings_seller_business_id'))
        batch_op.drop_index('ix_listings_material_status')
        batch_op.drop_index(batch_op.f('ix_listings_district'))

    op.drop_table('listings')
    op.drop_table('business_receiving_processes')
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_supabase_user_id'))
        batch_op.drop_index(batch_op.f('ix_app_users_email'))
        batch_op.drop_index(batch_op.f('ix_app_users_business_id'))

    op.drop_table('app_users')
    op.drop_table('symbiosis_pathways')
    op.drop_table('receiving_process_materials')
    with op.batch_alter_table('material_compatibility_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_compatibility_flags_material_id'))

    op.drop_table('material_compatibility_flags')
    op.drop_table('material_aliases')
    with op.batch_alter_table('enterprise_byproducts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enterprise_byproducts_enterprise_id'))

    op.drop_table('enterprise_byproducts')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_enterprise_id'))

    op.drop_table('businesses')
    op.drop_table('receiving_processes')
    op.drop_table('materials')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_business_id'))

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('enterprises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enterprises_nic5_code'))
        batch_op.drop_index(batch_op.f('ix_enterprises_nic2_division'))
        batch_op.drop_index(batch_op.f('ix_enterprises_district'))

    op.drop_table('enterprises')
    op.drop_table('districts')
    op.drop_table('district_distances')
    # ### end Alembic commands ###
